import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { verifyAuth } from '@/lib/auth';
import { logout } from '@/actions/auth-actions';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PnP App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const auth = await verifyAuth();

  return (
    <html lang="en">
      <body className={inter.className}>
      {auth && auth.user ? (
      <header id="auth-header">
        <form action={logout}>
          <button>Logout</button>
        </form>
      </header>
      ) :
      (
      <header id="auth-header">
        <p>Login first!</p>
      </header>
      )}
        {children}</body>
    </html>
  );
}